import {Header} from "@/components/shared/header";
import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Next Pizza",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
    modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
    return (
        <>
            <Header/>
            <main className="min-h-screen">
                <div>{children}
                    {modal}
                </div>
            </main>

        </>


    );
}
